### ISSUE TITLE
[프론트] 관리자의 게시물 자동 관리

### ISSUE THREAD

**Issue by sonjiseokk** [sonjiseokk/enjoy-trip-vue#2]
## ⛏ 작업 사항
- 현재 게시물 관리는 "관리자의 수동 승인" 이 가능한 구조
- 관리자가 굳이 수동 승인을 해야할 까?
- 그냥 일정 수치 이상은 자동으로 삭제 시키는 것도 괜찮을 듯

## 📝 작업 요약
- 

## 💡 관련 이슈
-

**Comment by YBK1** [comment]
- 현재 게시판 필터링 까지는 구현되어있음
- 게시판 필터링을 자동으로 진행하되 필터에 걸리는 것이 일정 횟수 이상 반복되면 해당 회원이 글작성하지 못하게 차단하고 해당 유저의 요청에 따라 관리자가 게시판을 확인하고 차단을 풀어주는 기능으로 진행하는 것도 괜찮을 듯
